import type { ComponentType } from "react";
import type { LucideProps } from "lucide-react";
import {
  BotIcon,
  ArchiveIcon,
  AlertCircleIcon,
  BellIcon,
  BoxIcon,
  CheckIcon,
  CheckCheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronsDownIcon,
  ChevronsUpDownIcon,
  CircleCheckIcon,
  CircleIcon,
  Clock3Icon,
  CommandIcon,
  CreditCardIcon,
  ExternalLinkIcon,
  FileArchiveIcon,
  FileCode2Icon,
  FileIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
  FolderIcon,
  GalleryVerticalEndIcon,
  ImageIcon,
  KanbanSquareIcon,
  LayoutDashboardIcon,
  LoaderCircleIcon,
  LogInIcon,
  LogOutIcon,
  MessageSquareIcon,
  MoreHorizontalIcon,
  MusicIcon,
  PaletteIcon,
  PanelLeftIcon,
  PaperclipIcon,
  PhoneIcon,
  PlusIcon,
  SearchIcon,
  SendHorizontalIcon,
  SettingsIcon,
  SlashIcon,
  SparklesIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  SunMoonIcon,
  VideoIcon,
  XIcon,
  UserCircleIcon,
  UserIcon,
  UsersIcon,
} from "lucide-react";

export type Icon = ComponentType<LucideProps>;

export const Icons = {
  alertCircle: AlertCircleIcon,
  check: CheckIcon,
  checks: CheckCheckIcon,
  circle: CircleIcon,
  circleCheck: CircleCheckIcon,
  clock: Clock3Icon,
  close: XIcon,
  code: FileCode2Icon,
  externalLink: ExternalLinkIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  chevronsDown: ChevronsDownIcon,
  chevronsUpDown: ChevronsUpDownIcon,
  dashboard: LayoutDashboardIcon,
  bot: BotIcon,
  kanban: KanbanSquareIcon,
  panelLeft: PanelLeftIcon,
  account: UserCircleIcon,
  profile: UserIcon,
  teams: UsersIcon,
  logo: CommandIcon,
  chat: MessageSquareIcon,
  notification: BellIcon,
  phone: PhoneIcon,
  video: VideoIcon,
  send: SendHorizontalIcon,
  paperclip: PaperclipIcon,
  add: PlusIcon,
  login: LogInIcon,
  logout: LogOutIcon,
  brightness: SunMoonIcon,
  palette: PaletteIcon,
  billing: CreditCardIcon,
  creditCard: CreditCardIcon,
  product: BoxIcon,
  sparkles: SparklesIcon,
  trendingDown: TrendingDownIcon,
  trendingUp: TrendingUpIcon,
  workspace: FolderIcon,
  slash: SlashIcon,
  media: ImageIcon,
  music: MusicIcon,
  page: FileIcon,
  post: FileTextIcon,
  fileTypeDoc: FileTextIcon,
  fileTypePdf: FileTextIcon,
  fileTypeXls: FileSpreadsheetIcon,
  fileZip: FileArchiveIcon,
  galleryVerticalEnd: GalleryVerticalEndIcon,
  spinner: LoaderCircleIcon,
  ellipsis: MoreHorizontalIcon,
  archive: ArchiveIcon,
  moreHorizontal: MoreHorizontalIcon,
} satisfies Record<string, Icon>;
